theme = "haruka-simple-theme"
baseURL = "https://shina346.github.io/haruka-simple-theme/"
title = "Haruka simple Blog Theme"
copyright = "2020"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
PaginatePath = ""

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    name = "Rss"
    url = "/index.xml"
    weight = 3
  [[menu.foot]]
    name = "2020"


[Author]
name = "Shina346"

[taxonomies]
category = "categories"
tag = "tags"